name: Send Telegram message on push

on:
  push:
    branches: [ main ]

jobs:
  send-telegram-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.AAGx-2U24wLgVYb9ATjDrsTQ7htRHhs7Sh8 }}
          TELEGRAM_CHAT_ID: "${{ secrets.joker77888hk }}"
          MESSAGE: "The wheel has been spun!"
        run: |
          curl -X POST "https://api.telegram.org/bot${AAGx-2U24wLgVYb9ATjDrsTQ7htRHhs7Sh8}/sendMessage" \
          -d "chat_id=${TELEGRAM_CHAT_ID}" \
          -d "text=${MESSAGE}"
